export default function FAQ() {
  const faqs = [
    { q: 'What is AI image metadata?', a: 'Hidden text data (prompts, model names, C2PA signatures) embedded inside images generated by AI tools like Midjourney, DALL-E, or Stable Diffusion.' },
    { q: 'Does removing metadata change image quality?', a: 'No. This tool only modifies text metadata attached to the file. The visual pixels remain 100% untouched and identical to the original.' },
    { q: 'What is C2PA metadata?', a: 'A cryptographic standard used by Adobe, Microsoft, and OpenAI to prove an image is AI-generated. This tool strips these JUMBF chunks from PNG files.' },
    { q: 'Is my image safe?', a: 'Yes. Images are processed in temporary server memory and immediately deleted after you download the cleaned result.' },
  ];

  const schema = {
    "@context": "https://schema.org", "@type": "FAQPage",
    "mainEntity": faqs.map(faq => ({ "@type": "Question", "name": faq.q, "acceptedAnswer": { "@type": "Answer", "text": faq.a } }))
  };

  return (
    <section className="divide-y divide-white/5">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      <div className="pb-6">
        <h2 className="text-4xl md:text-5xl font-black tracking-tighter text-white/10">FAQ</h2>
      </div>
      {faqs.map((faq, i) => (
        <details key={i} className="group py-6 cursor-pointer">
          <summary className="flex items-center justify-between text-lg md:text-xl font-medium text-white/60 group-hover:text-white transition-colors duration-300">
            {faq.q}
            <span className="text-xl text-white/20 group-hover:text-lime-400 group-open:rotate-45 transition-all duration-300 ml-4">+</span>
          </summary>
          <div className="mt-4 text-sm text-white/30 leading-relaxed max-w-2xl pr-12">
            {faq.a}
          </div>
        </details>
      ))}
    </section>
  );
}