export default function SeoContent() {
  return (
    <section className="max-w-6xl mx-auto px-6 space-y-32 py-24">
      
      {/* Block 1: What is it */}
      <div className="grid md:grid-cols-2 gap-16 items-start">
        <div>
          <p className="text-xs font-bold tracking-[0.3em] text-lime-400 uppercase mb-4">Understanding AI Data</p>
          <h2 className="text-4xl md:text-5xl font-black tracking-tighter leading-[0.9]">
            What is AI Image Metadata?
          </h2>
        </div>
        <div className="space-y-6 text-white/40 leading-relaxed text-sm border-t border-white/5 pt-8">
          <p>When you generate an image using tools like Midjourney, DALL-E 3, or Stable Diffusion, these platforms secretly embed metadata directly into the file. This isn&apos;t just simple EXIF data; it includes the exact text prompts you used, the model version, seed numbers, and CFG scales.</p>
          <p>More importantly, major tech companies are now embedding <span className="text-white/80 font-medium">C2PA (Coalition for Content Provenance and Authenticity)</span> signatures. This is a cryptographic manifest that acts as an unalterable digital fingerprint, proving to platforms like Facebook, Instagram, and Google that the image was generated by AI.</p>
          <p>This metadata travels with the image forever, even if you screenshot it, until it is explicitly stripped out using a tool like this one.</p>
        </div>
      </div>

      {/* Block 2: Why Remove It */}
      <div className="grid md:grid-cols-3 gap-8">
        <div className="md:col-span-1">
          <p className="text-xs font-bold tracking-[0.3em] text-lime-400 uppercase mb-4">The Problem</p>
          <h2 className="text-4xl font-black tracking-tighter leading-[0.9]">
            Why Strip Metadata?
          </h2>
        </div>
        <div className="md:col-span-2 grid sm:grid-cols-2 gap-6">
          {[
            { title: "Bypass AI Filters", desc: "Social media platforms automatically flag or down-rank images with C2PA data. Removing it allows your art to be treated like traditional digital art." },
            { title: "Protect Prompts", desc: "Your prompts are your intellectual property. AI metadata often stores them in plain text, allowing anyone to steal your exact workflow." },
            { title: "Clean Portfolios", desc: "If you use AI as a base for digital painting or heavy editing, you don't want clients seeing raw AI generation parameters." },
            { title: "Reduce File Size", desc: "C2PA manifests and deep EXIF data can bloat image files by 50-100kb. Stripping them optimizes your website load times." }
          ].map((item) => (
            <div key={item.title} className="border border-white/5 p-6 rounded-2xl hover:border-lime-400/20 transition-colors group">
              <h3 className="text-sm font-bold text-white/80 mb-2 group-hover:text-lime-400 transition-colors">{item.title}</h3>
              <p className="text-xs text-white/30 leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Block 3: Supported Formats (Good for long-tail SEO keywords) */}
      <div className="border border-white/5 rounded-3xl p-8 md:p-12 bg-white/[0.02]">
        <h2 className="text-3xl font-black tracking-tighter mb-8">Supported Formats & Signatures</h2>
        <div className="grid md:grid-cols-2 gap-12 text-sm">
          <div>
            <h3 className="text-xs font-bold text-white/50 tracking-widest mb-4">PNG FILES</h3>
            <ul className="space-y-3 text-white/40">
              <li className="flex items-start gap-3"><span className="text-lime-400 mt-1">+</span> Standard EXIF & Text Chunks (tEXt, zTXt, iTXt)</li>
              <li className="flex items-start gap-3"><span className="text-lime-400 mt-1">+</span> C2PA / JUMBF Manifests (caBX chunks)</li>
              <li className="flex items-start gap-3"><span className="text-lime-400 mt-1">+</span> Stable Diffusion / ComfyUI / A1111 WebUI parameters</li>
              <li className="flex items-start gap-3"><span className="text-lime-400 mt-1">+</span> Custom AI tool annotations</li>
            </ul>
          </div>
          <div>
            <h3 className="text-xs font-bold text-white/50 tracking-widest mb-4">JPEG / JPG FILES</h3>
            <ul className="space-y-3 text-white/40">
              <li className="flex items-start gap-3"><span className="text-lime-400 mt-1">+</span> EXIF 2.3 Standard Metadata</li>
              <li className="flex items-start gap-3"><span className="text-lime-400 mt-1">+</span> Adobe XMP Metadata Packets</li>
              <li className="flex items-start gap-3"><span className="text-lime-400 mt-1">+</span> IPTC-IIM Photo Metadata</li>
              <li className="flex items-start gap-3"><span className="text-lime-400 mt-1">+</span> Embedded User Comments (AI Prompts)</li>
            </ul>
          </div>
        </div>
      </div>

    </section>
  );
}